# ************** Tasks included in this playbook *********************
# 1. Update the repo
# 2. Install Java Runtime Environment (JRE) for Jenkins slave connectivity
# 3. Download Maven Package
# 4. Extract Maven package to /opt
# 5. Download latest OpenJDK 17 JDK for application builds
# 6. Extract the downloaded OpenJDK package to /opt
# 7. Rename extracted JDK directory to /opt/jdk-17
# 8. Create Jenkins working directory
---
- hosts: jenkins_slave
  become: true

  vars:
    user_name: karrireddy

  tasks:

    # Update Ubuntu package repository cache
    - name: Update ubuntu apt repository
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # Install Java Runtime Environment (JRE) from Ubuntu repository.
    # This contains only JRE (Not full JDK).
    # Jenkins slave uses this Java runtime to communicate with Jenkins master.
    - name: Install Java Runtime Environment
      apt:
        name: openjdk-21-jre
        state: present

    # Download Apache Maven package
    - name: Download Maven package
      get_url:
        url: https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
        dest: /opt

    # Extract Maven package that is already exits on the remote machine into /opt directory
    - name: Extract Maven package
      unarchive:
        src: /opt/apache-maven-3.8.8-bin.tar.gz
        dest: /opt/
        remote_src: yes

    # Download and install separate OpenJDK manually for application builds.
    # This is a full JDK (contains javac compiler, development tools, etc.).
    # Maven and Jenkins build jobs use this JDK for compiling/building Java applications.
    # Installed manually under /opt for fixed version control and custom JAVA_HOME configuration.
    - name: Download OpenJDK 17
      get_url:
        url: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.16%2B8/OpenJDK17U-jdk_x64_linux_hotspot_17.0.16_8.tar.gz
        dest: /opt

    # Extract downloaded OpenJDK package that is already exits on the remote machine  
    - name: Extract Java package
      unarchive:
        src: /opt/OpenJDK17U-jdk_x64_linux_hotspot_17.0.16_8.tar.gz
        dest: /opt/
        remote_src: yes

    # Rename extracted JDK directory to a standardized name
    # Easier for JAVA_HOME configuration and future upgrades
    - name: Rename extracted JDK directory
      command: mv /opt/jdk-17.0.16+8 /opt/jdk-17
      args:
        creates: /opt/jdk-17

    # Create Jenkins working directory
    - name: Create Jenkins directory
      file:
        path: "/home/{{ user_name }}/jenkins"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: true  #ensures ownership is applied recursively


      
