# ************** Tasks included in this playbook *********************
# 1. Update the repo
# 2. Install Java (openjdk-17-jre), so that the jenkins-slave can be configured to jenkins-master
# 3. Download Maven Package (Maven version 3.8.8)
# 4. Extract the downloaded maven package to /opt
# 5. Download openjdk 17 to configure application
# 6. Extract the downloaded openjdk 17 package to /opt
# 7. Rename the extracted openjdk directory name from jdk-17.0.2 to jdk-17
---
- hosts: jenkins_slave
  become: true
  vars:
    user_name: karrireddy
  tasks:
  - name: Update ubuntu apt repository
    apt:
      update_cache: yes
      cache_valid_time: 3600 #the time is in seconds, after which the cache is considered as outdated
  - name: Install java
    # apt install fontconfig openjdk-21-jre
    apt: #ansible.builtin.apt:
           # Install Java Runtime Environment (JRE) from Ubuntu repository.
           # This contains only JRE(Not full JDK)
           # This Java is mainly required for Jenkins agent/slave connectivity with Jenkins master.
           # Jenkins slave uses this Java runtime to start and communicate with Jenkins master.
      name: openjdk-21-jre 
      state: present #default value is present
  - name: Install maven
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.9/binaries/apache-maven-3.8.9-bin.tar.gz
      dest: /opt
  - name: Extract the maven package
    unarchive: # unarchive file that is already on the remote machine  
      src: /opt/apache-maven-3.8.9-bin.tar.gz
      dest: /opt/
      remote_src: yes  
  - name: Download openjdk 17
    get_url: 
          # Download and install a separate OpenJDK manually for application builds.
          # This is a full JDK (contains javac compiler, development tools, etc.).
          # Maven and Jenkins build jobs use this JDK for compiling/building Java applications.
          # Installed manually under /opt for fixed version control and custom JAVA_HOME configuration. 
      url: https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
      dest: /opt
  - name: Extract the java package
    unarchive: # unarchive file that is already on the remote machine  
      src: /opt/openjdk-17.0.2_linux-x64_bin.tar.gz
      dest: /opt/
      remote_src: yes     
  - name: Move openjdk-17.0.2 to jdk-17
    command: mv /opt/jdk-17.0.2 /opt/jdk-17
    args:
      creates: /opt/jdk-17
  - name: Create /home/{{ user_name }}/jenkins directory(home directory for jenkins-slave)
    file:
      path: "/home/{{ user_name }}/jenkins"
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"  
      recurse: true #ensures ownership is applied recursively

      
