---
- name: Install kubectl on Jenkins slave
  hosts: jenkins_slave
  become: true

  tasks:

    - name: Download kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/v1.33.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
        owner: root
        group: root

    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_output

    - name: Display kubectl version
      debug:
        var: kubectl_output.stdout