---
- name: Install Helm
  hosts: jenkins_slave
  become: yes
  tasks:
  - name: Update apt package manager
    apt:
      update_cache: yes
  - name: Install the dependencies
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
      state: present
  - name: Download helm install script
    get_url:
      url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      dest: /tmp/get_helm.sh
      mode: 0755
  - name: Run the helm install script
    command: /tmp/get_helm.sh
    args:
      creates: /usr/local/bin/helm
  - name: Verify helm installation
    command: helm version
    register: helm_version
  - name: Display Helm version
    debug: 
      var: helm_version.stdout_lines        